### ISSUE TITLE
Add More Java Programs

### ISSUE THREAD

**Issue by DarkPhoenix2704** [DarkPhoenix2704/LearnJava#1]
Currently there is only one Program.
I want to expand it to many
Let it be small or big code . We need your contribution

**Comment by z3n70** [comment]
@DarkPhoenix2704 can u assign me?

**Comment by DarkPhoenix2704** [comment]
Sure

**Comment by z3n70** [comment]
@DarkPhoenix2704 i have finished it, pls review my PR :)

**Comment by shrishtickling** [comment]
Hello! Could you please assign it to me?

**Comment by clintondsza** [comment]
@DarkPhoenix2704 could you please assign it to me too?
